JDP240201-20 User Test Suite
piotr-grosicki/project-jdp-2402-01 pull request #18
Opened 2024-03-16 06:58 UTC by TomaszZajdek

mam nadzieje ze spoko, myslalem nad uzyciem afterEach do cleanup ale nie wiem jaka jest konwencja

2024-03-17 01:56 UTC, JakubWaw93 requested changes

2024-03-17 01:56 UTC, JakubWaw93 commented on src/test/java/com/kodilla/ecommercee/domainTests/UserTestSuite.java
> +        userRepository.save(savedUser);
Przepisaliśmy w repository metodę delete, i teraz możemy robić te dwie rzeczy, czyli setActive(false) i save właśnie tą jedną metodą.

2024-03-18 16:03 UTC, TomaszZajdek commented
zmienilem na delete

2024-03-18 21:18 UTC, JakubWaw93 approved these changes

2024-03-18 21:23 UTC, baku09 approved these changes

2024-03-19 11:32 UTC, merged