JDP240201-24_OrderController_finalization
piotr-grosicki/project-jdp-2402-01 pull request #35
Opened 2024-03-22 18:12 UTC by ZuzaJaworska

OrderController finalization without CartController finalized - Postman test needed with CartController merged

2024-03-22 20:02 UTC, JakubWaw93 commented on src/main/java/com/kodilla/ecommercee/exception/OrderNotFoundException.java
> +public class OrderNotFoundException extends RuntimeException {
Dlaczego ? i dlaczego ja też muszę to teraz pozmieniać ? :)

2024-03-22 20:06 UTC, ZuzaJaworska commented on src/main/java/com/kodilla/ecommercee/exception/OrderNotFoundException.java
> +public class OrderNotFoundException extends RuntimeException {
bo tak mi powiedział internet, że ten exception ma największy sens :p ale wiesz, w tym przypadku, to nie zależy mi żeby się jakoś specjalnie kłócić :D

2024-03-24 22:58 UTC, JakubWaw93 requested changes
Dropnij wszystkie tabele, coś w nich jest nie tak, tzn może tylko u mnie, ale możliwe że nie tylko ja wykonałem jakąś błędną sekwencję,  niech hibernate sam sobie je na nowo namaluje. Jak to zrobisz, i ten error z shared references poprawisz,  tworzenie orderu z koszyka powinno zadziałać.

2024-03-24 22:58 UTC, JakubWaw93 commented on src/main/java/com/kodilla/ecommercee/service/OrderService.java
> +        order.setProducts(cart.getProducts());
Tutaj musisz zrobić:
order.setProducts(new ArrayList<>(cart.getProducts()));
inaczej Hibernate będzie wiecznie narzekał na shared references.

2024-03-24 22:58 UTC, JakubWaw93 commented on src/main/java/com/kodilla/ecommercee/service/OrderService.java
> +        order.setActive(true);
Order od razu chyba ma active na true ustawione w momencie tworzenia objektu.
Ale będzie trzeba dodać order number bo też jest nullable = false.
to z datą co pisałem albo cokolwiek :).

2024-03-25 20:57 UTC, JakubWaw93 approved these changes
Bravo

2024-03-25 21:07 UTC, baku09 commented
pięknie

2024-03-25 21:07 UTC, baku09 approved these changes

2024-03-25 21:07 UTC, Ayuru approved these changes
Sprawdzone Postmanem, działa. : >

2024-03-25 21:07 UTC, merged